# Generated by Django 4.1.3 on 2022-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.FloatField(verbose_name='Length')),
                ('Breadth', models.FloatField(verbose_name='Breadth')),
                ('height', models.FloatField(verbose_name='height')),
            ],
        ),
    ]
